[2024-05-27T22:14:34.204+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_load_stage_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-27T22:14:34.217+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_load_stage_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-27T22:14:34.217+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-27T22:14:34.217+0000] {taskinstance.py:1284} INFO - Starting attempt 7 of 7
[2024-05-27T22:14:34.217+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-27T22:14:34.237+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): ti_load_stage_data> on 2024-05-27 21:49:08.726117+00:00
[2024-05-27T22:14:34.244+0000] {standard_task_runner.py:55} INFO - Started process 11044 to run task
[2024-05-27T22:14:34.247+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_lookup_ingest', 'ti_load_stage_data', 'manual__2024-05-27T21:49:08.726117+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmpmmmsafl8']
[2024-05-27T22:14:34.248+0000] {standard_task_runner.py:83} INFO - Job 93: Subtask ti_load_stage_data
[2024-05-27T22:14:34.321+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_lookup_ingest.ti_load_stage_data manual__2024-05-27T21:49:08.726117+00:00 [running]> on host a64b6410e10e
[2024-05-27T22:14:34.412+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_lookup_ingest
AIRFLOW_CTX_TASK_ID=ti_load_stage_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-27T21:49:08.726117+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-27T21:49:08.726117+00:00
[2024-05-27T22:14:34.439+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-27T22:14:37.473+0000] {docker.py:354} INFO - [0m22:14:37  Running with dbt=1.5.11
[2024-05-27T22:14:37.641+0000] {docker.py:354} INFO - [0m22:14:37  Registered adapter: postgres=1.5.11
[2024-05-27T22:14:37.774+0000] {docker.py:354} INFO - [0m22:14:37  Found 3 models, 4 tests, 0 snapshots, 0 analyses, 310 macros, 0 operations, 1 seed file, 1 source, 0 exposures, 0 metrics, 0 groups
[2024-05-27T22:14:37.777+0000] {docker.py:354} INFO - [0m22:14:37
[2024-05-27T22:14:37.868+0000] {docker.py:354} INFO - [0m22:14:37  Concurrency: 4 threads (target='dev')
[2024-05-27T22:14:37.869+0000] {docker.py:354} INFO - [0m22:14:37
[2024-05-27T22:14:37.874+0000] {docker.py:354} INFO - [0m22:14:37  1 of 1 START sql table model dev.silver_covid_geo .............................. [RUN]
[2024-05-27T22:14:38.132+0000] {docker.py:354} INFO - [0m22:14:38  1 of 1 ERROR creating sql table model dev.silver_covid_geo ..................... [[31mERROR[0m in 0.25s]
[2024-05-27T22:14:38.198+0000] {docker.py:354} INFO - [0m22:14:38
[2024-05-27T22:14:38.199+0000] {docker.py:354} INFO - [0m22:14:38  Finished running 1 table model in 0 hours 0 minutes and 0.42 seconds (0.42s).
[2024-05-27T22:14:38.213+0000] {docker.py:354} INFO - [0m22:14:38
[2024-05-27T22:14:38.213+0000] {docker.py:354} INFO - [0m22:14:38  [31mCompleted with 1 error and 0 warnings:[0m
[2024-05-27T22:14:38.214+0000] {docker.py:354} INFO - [0m22:14:38
[2024-05-27T22:14:38.215+0000] {docker.py:354} INFO - [0m22:14:38  [33mDatabase Error in model silver_covid_geo (models/silver/silver_covid_geo.sql)[0m
[2024-05-27T22:14:38.216+0000] {docker.py:354} INFO - [0m22:14:38    column "Lat" does not exist
[2024-05-27T22:14:38.216+0000] {docker.py:354} INFO - [0m22:14:38    LINE 1169: where "Lat" is not null
[2024-05-27T22:14:38.217+0000] {docker.py:354} INFO - [0m22:14:38                     ^
[2024-05-27T22:14:38.218+0000] {docker.py:354} INFO - [0m22:14:38    HINT:  Perhaps you meant to reference the column "silver_dataset.lat".
[2024-05-27T22:14:38.219+0000] {docker.py:354} INFO - [0m22:14:38    compiled Code at target/run/franko/models/silver/silver_covid_geo.sql
[2024-05-27T22:14:38.219+0000] {docker.py:354} INFO - [0m22:14:38
[2024-05-27T22:14:38.220+0000] {docker.py:354} INFO - [0m22:14:38  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-05-27T22:14:39.269+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 430, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 303, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 359, in _run_image_with_mounts
    raise AirflowException(f"Docker container failed: {repr(result)} lines {joined_log_lines}")
airflow.exceptions.AirflowException: Docker container failed: {'StatusCode': 1} lines [0m22:14:37  Running with dbt=1.5.11
[0m22:14:37  Registered adapter: postgres=1.5.11
[0m22:14:37  Found 3 models, 4 tests, 0 snapshots, 0 analyses, 310 macros, 0 operations, 1 seed file, 1 source, 0 exposures, 0 metrics, 0 groups
[0m22:14:37
[0m22:14:37  Concurrency: 4 threads (target='dev')
[0m22:14:37
[0m22:14:37  1 of 1 START sql table model dev.silver_covid_geo .............................. [RUN]
[0m22:14:38  1 of 1 ERROR creating sql table model dev.silver_covid_geo ..................... [[31mERROR[0m in 0.25s]
[0m22:14:38
[0m22:14:38  Finished running 1 table model in 0 hours 0 minutes and 0.42 seconds (0.42s).
[0m22:14:38
[0m22:14:38  [31mCompleted with 1 error and 0 warnings:[0m
[0m22:14:38
[0m22:14:38  [33mDatabase Error in model silver_covid_geo (models/silver/silver_covid_geo.sql)[0m
[0m22:14:38    column "Lat" does not exist
[0m22:14:38    LINE 1169: where "Lat" is not null
[0m22:14:38                     ^
[0m22:14:38    HINT:  Perhaps you meant to reference the column "silver_dataset.lat".
[0m22:14:38    compiled Code at target/run/franko/models/silver/silver_covid_geo.sql
[0m22:14:38
[0m22:14:38  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-05-27T22:14:39.274+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=franko_lookup_ingest, task_id=ti_load_stage_data, execution_date=20240527T214908, start_date=20240527T221434, end_date=20240527T221439
[2024-05-27T22:14:39.295+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 93 for task ti_load_stage_data (Docker container failed: {'StatusCode': 1} lines [0m22:14:37  Running with dbt=1.5.11
[0m22:14:37  Registered adapter: postgres=1.5.11
[0m22:14:37  Found 3 models, 4 tests, 0 snapshots, 0 analyses, 310 macros, 0 operations, 1 seed file, 1 source, 0 exposures, 0 metrics, 0 groups
[0m22:14:37
[0m22:14:37  Concurrency: 4 threads (target='dev')
[0m22:14:37
[0m22:14:37  1 of 1 START sql table model dev.silver_covid_geo .............................. [RUN]
[0m22:14:38  1 of 1 ERROR creating sql table model dev.silver_covid_geo ..................... [[31mERROR[0m in 0.25s]
[0m22:14:38
[0m22:14:38  Finished running 1 table model in 0 hours 0 minutes and 0.42 seconds (0.42s).
[0m22:14:38
[0m22:14:38  [31mCompleted with 1 error and 0 warnings:[0m
[0m22:14:38
[0m22:14:38  [33mDatabase Error in model silver_covid_geo (models/silver/silver_covid_geo.sql)[0m
[0m22:14:38    column "Lat" does not exist
[0m22:14:38    LINE 1169: where "Lat" is not null
[0m22:14:38                     ^
[0m22:14:38    HINT:  Perhaps you meant to reference the column "silver_dataset.lat".
[0m22:14:38    compiled Code at target/run/franko/models/silver/silver_covid_geo.sql
[0m22:14:38
[0m22:14:38  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1; 11044)
[2024-05-27T22:14:39.303+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-05-27T22:14:39.322+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
