[2024-05-28T01:51:17.159+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_load_target_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-28T01:51:17.183+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_load_target_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-28T01:51:17.184+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T01:51:17.184+0000] {taskinstance.py:1284} INFO - Starting attempt 10 of 10
[2024-05-28T01:51:17.184+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T01:51:17.207+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): ti_load_target_data> on 2024-05-27 21:49:08.726117+00:00
[2024-05-28T01:51:17.216+0000] {standard_task_runner.py:55} INFO - Started process 4882 to run task
[2024-05-28T01:51:17.222+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_lookup_ingest', 'ti_load_target_data', 'manual__2024-05-27T21:49:08.726117+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmp1j9rrhvo']
[2024-05-28T01:51:17.223+0000] {standard_task_runner.py:83} INFO - Job 186: Subtask ti_load_target_data
[2024-05-28T01:51:17.309+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_lookup_ingest.ti_load_target_data manual__2024-05-27T21:49:08.726117+00:00 [running]> on host a64b6410e10e
[2024-05-28T01:51:17.448+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_lookup_ingest
AIRFLOW_CTX_TASK_ID=ti_load_target_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-27T21:49:08.726117+00:00
AIRFLOW_CTX_TRY_NUMBER=10
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-27T21:49:08.726117+00:00
[2024-05-28T01:51:17.548+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-28T01:51:20.796+0000] {docker.py:354} INFO - [0m01:51:20  Running with dbt=1.5.11
[2024-05-28T01:51:20.917+0000] {docker.py:354} INFO - [0m01:51:20  Registered adapter: postgres=1.5.11
[2024-05-28T01:51:21.042+0000] {docker.py:354} INFO - [0m01:51:21  Found 5 models, 4 tests, 0 snapshots, 0 analyses, 422 macros, 0 operations, 1 seed file, 1 source, 0 exposures, 0 metrics, 0 groups
[2024-05-28T01:51:21.043+0000] {docker.py:354} INFO - [0m01:51:21
[2024-05-28T01:51:21.141+0000] {docker.py:354} INFO - [0m01:51:21  Concurrency: 4 threads (target='dev')
[2024-05-28T01:51:21.141+0000] {docker.py:354} INFO - [0m01:51:21
[2024-05-28T01:51:21.144+0000] {docker.py:354} INFO - [0m01:51:21  1 of 1 START sql table model dev.golden_data ................................... [RUN]
[2024-05-28T01:51:21.360+0000] {docker.py:354} INFO - [0m01:51:21  1 of 1 ERROR creating sql table model dev.golden_data .......................... [[31mERROR[0m in 0.21s]
[2024-05-28T01:51:21.460+0000] {docker.py:354} INFO - [0m01:51:21
[2024-05-28T01:51:21.460+0000] {docker.py:354} INFO - [0m01:51:21  Finished running 1 table model in 0 hours 0 minutes and 0.42 seconds (0.42s).
[2024-05-28T01:51:21.470+0000] {docker.py:354} INFO - [0m01:51:21
[2024-05-28T01:51:21.470+0000] {docker.py:354} INFO - [0m01:51:21  [31mCompleted with 1 error and 0 warnings:[0m
[2024-05-28T01:51:21.471+0000] {docker.py:354} INFO - [0m01:51:21
[2024-05-28T01:51:21.471+0000] {docker.py:354} INFO - [0m01:51:21  [33mDatabase Error in model golden_data (models/golden/golden_data.sql)[0m
[2024-05-28T01:51:21.471+0000] {docker.py:354} INFO - [0m01:51:21    function len(integer) does not exist
[2024-05-28T01:51:21.471+0000] {docker.py:354} INFO - [0m01:51:21    LINE 20:     substr(covid_for_date_value,5,len(covid_for_date_value))...
[2024-05-28T01:51:21.472+0000] {docker.py:354} INFO - [0m01:51:21                                               ^
[2024-05-28T01:51:21.472+0000] {docker.py:354} INFO - [0m01:51:21    HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[2024-05-28T01:51:21.472+0000] {docker.py:354} INFO - [0m01:51:21    compiled Code at target/run/franko/models/golden/golden_data.sql
[2024-05-28T01:51:21.472+0000] {docker.py:354} INFO - [0m01:51:21
[2024-05-28T01:51:21.473+0000] {docker.py:354} INFO - [0m01:51:21  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-05-28T01:51:22.488+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 430, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 303, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 359, in _run_image_with_mounts
    raise AirflowException(f"Docker container failed: {repr(result)} lines {joined_log_lines}")
airflow.exceptions.AirflowException: Docker container failed: {'StatusCode': 1} lines [0m01:51:20  Running with dbt=1.5.11
[0m01:51:20  Registered adapter: postgres=1.5.11
[0m01:51:21  Found 5 models, 4 tests, 0 snapshots, 0 analyses, 422 macros, 0 operations, 1 seed file, 1 source, 0 exposures, 0 metrics, 0 groups
[0m01:51:21
[0m01:51:21  Concurrency: 4 threads (target='dev')
[0m01:51:21
[0m01:51:21  1 of 1 START sql table model dev.golden_data ................................... [RUN]
[0m01:51:21  1 of 1 ERROR creating sql table model dev.golden_data .......................... [[31mERROR[0m in 0.21s]
[0m01:51:21
[0m01:51:21  Finished running 1 table model in 0 hours 0 minutes and 0.42 seconds (0.42s).
[0m01:51:21
[0m01:51:21  [31mCompleted with 1 error and 0 warnings:[0m
[0m01:51:21
[0m01:51:21  [33mDatabase Error in model golden_data (models/golden/golden_data.sql)[0m
[0m01:51:21    function len(integer) does not exist
[0m01:51:21    LINE 20:     substr(covid_for_date_value,5,len(covid_for_date_value))...
[0m01:51:21                                               ^
[0m01:51:21    HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[0m01:51:21    compiled Code at target/run/franko/models/golden/golden_data.sql
[0m01:51:21
[0m01:51:21  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-05-28T01:51:22.491+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=franko_lookup_ingest, task_id=ti_load_target_data, execution_date=20240527T214908, start_date=20240528T015117, end_date=20240528T015122
[2024-05-28T01:51:22.502+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 186 for task ti_load_target_data (Docker container failed: {'StatusCode': 1} lines [0m01:51:20  Running with dbt=1.5.11
[0m01:51:20  Registered adapter: postgres=1.5.11
[0m01:51:21  Found 5 models, 4 tests, 0 snapshots, 0 analyses, 422 macros, 0 operations, 1 seed file, 1 source, 0 exposures, 0 metrics, 0 groups
[0m01:51:21
[0m01:51:21  Concurrency: 4 threads (target='dev')
[0m01:51:21
[0m01:51:21  1 of 1 START sql table model dev.golden_data ................................... [RUN]
[0m01:51:21  1 of 1 ERROR creating sql table model dev.golden_data .......................... [[31mERROR[0m in 0.21s]
[0m01:51:21
[0m01:51:21  Finished running 1 table model in 0 hours 0 minutes and 0.42 seconds (0.42s).
[0m01:51:21
[0m01:51:21  [31mCompleted with 1 error and 0 warnings:[0m
[0m01:51:21
[0m01:51:21  [33mDatabase Error in model golden_data (models/golden/golden_data.sql)[0m
[0m01:51:21    function len(integer) does not exist
[0m01:51:21    LINE 20:     substr(covid_for_date_value,5,len(covid_for_date_value))...
[0m01:51:21                                               ^
[0m01:51:21    HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[0m01:51:21    compiled Code at target/run/franko/models/golden/golden_data.sql
[0m01:51:21
[0m01:51:21  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1; 4882)
[2024-05-28T01:51:22.543+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-05-28T01:51:22.571+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
