[2024-05-27T20:54:44.986+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.ti_create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-27T20:54:44.998+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.ti_create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-27T20:54:44.999+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-27T20:54:44.999+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-05-27T20:54:44.999+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-27T20:54:45.015+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): ti_create_seeds> on 2024-05-25 02:02:40.608195+00:00
[2024-05-27T20:54:45.021+0000] {standard_task_runner.py:55} INFO - Started process 4649 to run task
[2024-05-27T20:54:45.024+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_python', 'ti_create_seeds', 'manual__2024-05-25T02:02:40.608195+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmpup8oa49v']
[2024-05-27T20:54:45.025+0000] {standard_task_runner.py:83} INFO - Job 78: Subtask ti_create_seeds
[2024-05-27T20:54:45.086+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_python.ti_create_seeds manual__2024-05-25T02:02:40.608195+00:00 [running]> on host a64b6410e10e
[2024-05-27T20:54:45.167+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_python
AIRFLOW_CTX_TASK_ID=ti_create_seeds
AIRFLOW_CTX_EXECUTION_DATE=2024-05-25T02:02:40.608195+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-25T02:02:40.608195+00:00
[2024-05-27T20:54:45.188+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-27T20:54:45.347+0000] {docker.py:354} INFO - --threads: 1: cd: can't cd to /dbt_directory/projects
[2024-05-27T20:54:45.391+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 430, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 303, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 359, in _run_image_with_mounts
    raise AirflowException(f"Docker container failed: {repr(result)} lines {joined_log_lines}")
airflow.exceptions.AirflowException: Docker container failed: {'StatusCode': 2} lines --threads: 1: cd: can't cd to /dbt_directory/projects
[2024-05-27T20:54:45.395+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=franko_python, task_id=ti_create_seeds, execution_date=20240525T020240, start_date=20240527T205444, end_date=20240527T205445
[2024-05-27T20:54:45.409+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 78 for task ti_create_seeds (Docker container failed: {'StatusCode': 2} lines --threads: 1: cd: can't cd to /dbt_directory/projects; 4649)
[2024-05-27T20:54:45.436+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-05-27T20:54:45.455+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
