[2024-05-27T18:28:59.445+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-27T18:28:59.457+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-27T18:28:59.458+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-27T18:28:59.458+0000] {taskinstance.py:1284} INFO - Starting attempt 24 of 24
[2024-05-27T18:28:59.458+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-27T18:28:59.476+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): create_seeds> on 2024-05-25 02:02:40.608195+00:00
[2024-05-27T18:28:59.483+0000] {standard_task_runner.py:55} INFO - Started process 1823 to run task
[2024-05-27T18:28:59.487+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_python', 'create_seeds', 'manual__2024-05-25T02:02:40.608195+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmp_3jp6co7']
[2024-05-27T18:28:59.488+0000] {standard_task_runner.py:83} INFO - Job 52: Subtask create_seeds
[2024-05-27T18:28:59.583+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [running]> on host b637b51b94ee
[2024-05-27T18:28:59.692+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_python
AIRFLOW_CTX_TASK_ID=create_seeds
AIRFLOW_CTX_EXECUTION_DATE=2024-05-25T02:02:40.608195+00:00
AIRFLOW_CTX_TRY_NUMBER=24
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-25T02:02:40.608195+00:00
[2024-05-27T18:28:59.724+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-27T18:29:01.938+0000] {docker.py:354} INFO - Usage: dbt run [OPTIONS]
Try 'dbt run -h' for help.

Error: Invalid value for '--project-dir': Path '/usr/app/projects/franko' does not exist.
[2024-05-27T18:29:02.101+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 430, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 303, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 359, in _run_image_with_mounts
    raise AirflowException(f"Docker container failed: {repr(result)} lines {joined_log_lines}")
airflow.exceptions.AirflowException: Docker container failed: {'StatusCode': 2} lines Usage: dbt run [OPTIONS]
Try 'dbt run -h' for help.

Error: Invalid value for '--project-dir': Path '/usr/app/projects/franko' does not exist.
[2024-05-27T18:29:02.105+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=franko_python, task_id=create_seeds, execution_date=20240525T020240, start_date=20240527T182859, end_date=20240527T182902
[2024-05-27T18:29:02.120+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 52 for task create_seeds (Docker container failed: {'StatusCode': 2} lines Usage: dbt run [OPTIONS]
Try 'dbt run -h' for help.

Error: Invalid value for '--project-dir': Path '/usr/app/projects/franko' does not exist.; 1823)
[2024-05-27T18:29:02.147+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-05-27T18:29:02.168+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
