[2024-05-25T05:41:33.702+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-25T05:41:33.712+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-25T05:41:33.713+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-25T05:41:33.713+0000] {taskinstance.py:1284} INFO - Starting attempt 6 of 6
[2024-05-25T05:41:33.713+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-25T05:41:33.728+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): create_seeds> on 2024-05-25 02:02:40.608195+00:00
[2024-05-25T05:41:33.734+0000] {standard_task_runner.py:55} INFO - Started process 852 to run task
[2024-05-25T05:41:33.737+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_python', 'create_seeds', 'manual__2024-05-25T02:02:40.608195+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmp64237r74']
[2024-05-25T05:41:33.737+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask create_seeds
[2024-05-25T05:41:33.797+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [running]> on host b637b51b94ee
[2024-05-25T05:41:33.878+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_python
AIRFLOW_CTX_TASK_ID=create_seeds
AIRFLOW_CTX_EXECUTION_DATE=2024-05-25T02:02:40.608195+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-25T02:02:40.608195+00:00
[2024-05-25T05:41:33.917+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-25T05:41:33.922+0000] {docker.py:295} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-05-25T05:41:37.477+0000] {docker.py:354} INFO - Usage: dbt run [OPTIONS]
Try 'dbt run -h' for help.
[2024-05-25T05:41:37.478+0000] {docker.py:354} INFO - Error: Invalid value for '--project-dir': Path '/usr/app/jazmi' does not exist.
[2024-05-25T05:41:37.703+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.43/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 291, in _run_image
    return self._run_image_with_mounts(self.mounts + [tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 344, in _run_image_with_mounts
    tty=self.tty,
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.43/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmpif0tbm9o")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 430, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 300, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 359, in _run_image_with_mounts
    raise AirflowException(f"Docker container failed: {repr(result)} lines {joined_log_lines}")
airflow.exceptions.AirflowException: Docker container failed: {'StatusCode': 2} lines Usage: dbt run [OPTIONS]
Try 'dbt run -h' for help.
Error: Invalid value for '--project-dir': Path '/usr/app/jazmi' does not exist.
[2024-05-25T05:41:37.714+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=franko_python, task_id=create_seeds, execution_date=20240525T020240, start_date=20240525T054133, end_date=20240525T054137
[2024-05-25T05:41:37.741+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 25 for task create_seeds (Docker container failed: {'StatusCode': 2} lines Usage: dbt run [OPTIONS]
Try 'dbt run -h' for help.
Error: Invalid value for '--project-dir': Path '/usr/app/jazmi' does not exist.; 852)
[2024-05-25T05:41:37.785+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-05-25T05:41:37.816+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
