[2024-05-25T05:54:20.354+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-25T05:54:20.366+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [queued]>
[2024-05-25T05:54:20.367+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-25T05:54:20.367+0000] {taskinstance.py:1284} INFO - Starting attempt 8 of 8
[2024-05-25T05:54:20.367+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-25T05:54:20.386+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): create_seeds> on 2024-05-25 02:02:40.608195+00:00
[2024-05-25T05:54:20.392+0000] {standard_task_runner.py:55} INFO - Started process 331 to run task
[2024-05-25T05:54:20.396+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_python', 'create_seeds', 'manual__2024-05-25T02:02:40.608195+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmpw_44hn3a']
[2024-05-25T05:54:20.397+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask create_seeds
[2024-05-25T05:54:20.473+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_python.create_seeds manual__2024-05-25T02:02:40.608195+00:00 [running]> on host b637b51b94ee
[2024-05-25T05:54:20.558+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_python
AIRFLOW_CTX_TASK_ID=create_seeds
AIRFLOW_CTX_EXECUTION_DATE=2024-05-25T02:02:40.608195+00:00
AIRFLOW_CTX_TRY_NUMBER=8
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-25T02:02:40.608195+00:00
[2024-05-25T05:54:20.584+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-25T05:54:23.984+0000] {docker.py:354} INFO - Usage: dbt run [OPTIONS]
Try 'dbt run -h' for help.

Error: Invalid value for '--project-dir': Path '/usr/app/projects/luis' does not exist.
[2024-05-25T05:54:24.178+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 430, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 303, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/docker/operators/docker.py", line 359, in _run_image_with_mounts
    raise AirflowException(f"Docker container failed: {repr(result)} lines {joined_log_lines}")
airflow.exceptions.AirflowException: Docker container failed: {'StatusCode': 2} lines Usage: dbt run [OPTIONS]
Try 'dbt run -h' for help.

Error: Invalid value for '--project-dir': Path '/usr/app/projects/luis' does not exist.
[2024-05-25T05:54:24.181+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=franko_python, task_id=create_seeds, execution_date=20240525T020240, start_date=20240525T055420, end_date=20240525T055424
[2024-05-25T05:54:24.197+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 29 for task create_seeds (Docker container failed: {'StatusCode': 2} lines Usage: dbt run [OPTIONS]
Try 'dbt run -h' for help.

Error: Invalid value for '--project-dir': Path '/usr/app/projects/luis' does not exist.; 331)
[2024-05-25T05:54:24.223+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-05-25T05:54:24.244+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
