[2024-05-28T02:54:39.645+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_test_stage_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-28T02:54:39.658+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: franko_lookup_ingest.ti_test_stage_data manual__2024-05-27T21:49:08.726117+00:00 [queued]>
[2024-05-28T02:54:39.659+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T02:54:39.660+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 3
[2024-05-28T02:54:39.660+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-05-28T02:54:39.691+0000] {taskinstance.py:1304} INFO - Executing <Task(DockerOperator): ti_test_stage_data> on 2024-05-27 21:49:08.726117+00:00
[2024-05-28T02:54:39.699+0000] {standard_task_runner.py:55} INFO - Started process 2183 to run task
[2024-05-28T02:54:39.712+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'franko_lookup_ingest', 'ti_test_stage_data', 'manual__2024-05-27T21:49:08.726117+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmp5hf9hqwf']
[2024-05-28T02:54:39.713+0000] {standard_task_runner.py:83} INFO - Job 238: Subtask ti_test_stage_data
[2024-05-28T02:54:39.834+0000] {task_command.py:389} INFO - Running <TaskInstance: franko_lookup_ingest.ti_test_stage_data manual__2024-05-27T21:49:08.726117+00:00 [running]> on host a64b6410e10e
[2024-05-28T02:54:39.970+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=franko_lookup_ingest
AIRFLOW_CTX_TASK_ID=ti_test_stage_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-27T21:49:08.726117+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-05-27T21:49:08.726117+00:00
[2024-05-28T02:54:40.004+0000] {docker.py:284} INFO - Starting docker container from image my_dbt
[2024-05-28T02:54:42.975+0000] {docker.py:354} INFO - [0m02:54:42  Running with dbt=1.5.11
[2024-05-28T02:54:43.131+0000] {docker.py:354} INFO - [0m02:54:43  Registered adapter: postgres=1.5.11
[2024-05-28T02:54:43.228+0000] {docker.py:354} INFO - [0m02:54:43  [[33mWARNING[0m]: Did not find matching node for patch with name 'silver_unpivot_covid_geo copy' in the 'models' section of file 'models/silver/silver_unpivot_covid_geo.yml'
[2024-05-28T02:54:43.273+0000] {docker.py:354} INFO - [0m02:54:43  [[33mWARNING[0m]: Test 'test.franko.not_null_silver_unpivot_covid_geo copy_transf_province_state.46bef1c987' (models/silver/silver_unpivot_covid_geo.yml) depends on a node named 'silver_unpivot_covid_geo copy' in package '' which was not found
[2024-05-28T02:54:43.274+0000] {docker.py:354} INFO - [0m02:54:43  [[33mWARNING[0m]: Test 'test.franko.not_null_silver_unpivot_covid_geo copy_Country_Region.ab60406998' (models/silver/silver_unpivot_covid_geo.yml) depends on a node named 'silver_unpivot_covid_geo copy' in package '' which was not found
[2024-05-28T02:54:43.301+0000] {docker.py:354} INFO - [0m02:54:43  Found 6 models, 4 tests, 0 snapshots, 0 analyses, 422 macros, 0 operations, 1 seed file, 1 source, 0 exposures, 0 metrics, 0 groups
[2024-05-28T02:54:43.303+0000] {docker.py:354} INFO - [0m02:54:43
[2024-05-28T02:54:43.304+0000] {docker.py:354} INFO - [0m02:54:43  Nothing to do. Try checking your model configs and model specification args
[2024-05-28T02:54:44.175+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=franko_lookup_ingest, task_id=ti_test_stage_data, execution_date=20240527T214908, start_date=20240528T025439, end_date=20240528T025444
[2024-05-28T02:54:44.223+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-05-28T02:54:44.244+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
